name: nemo_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  serverpod: 1.2.5
  mailer: 6.1.0 

dev_dependencies:
  lints: ^3.0.0
